# Generated by Django 5.0.2 on 2024-04-17 19:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0003_profile_favourites"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="email",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="last_name",
        ),
    ]
