# Generated by Django 5.0.2 on 2024-04-19 11:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0004_remove_profile_email_remove_profile_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(blank=True, max_length=50, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="profile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=50, verbose_name="Phone"),
        ),
        migrations.AddField(
            model_name="profile",
            name="postal_code",
            field=models.CharField(blank=True, max_length=50, verbose_name="Postcode"),
        ),
        migrations.AddField(
            model_name="profile",
            name="shipping_address",
            field=models.CharField(blank=True, max_length=50, verbose_name="Address"),
        ),
    ]
