# Generated by Django 5.0.2 on 2024-03-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, default='default_cat.png', upload_to='category/%Y/%m/%d', verbose_name='Image'),
        ),
    ]
